name: Dart CI
defaults:
  run:
    working-directory: ./codevid_live_app
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cd ./codevid_live_app && pub get
    - name: Run tests
      run: pub run test
